name: my_template
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  clipboard: ^0.1.3
  fluttertoast: ^8.2.4
  flutter_screenutil: ^5.8.1
  font_awesome_flutter: ^10.2.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  logger: ^1.1.0
  path_provider: ^2.0.9
  provider: ^6.0.0
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  url_launcher: ^6.0.10
  local_auth: ^2.1.7
  flutter_html: ^3.0.0-beta.1
  paginable: ^2.0.0
  onesignal_flutter: ^3.4.1
  firebase_core: ^2.4.1
  firebase_remote_config: ^4.2.0
  permission_handler: ^10.0.0
  connectivity_plus:
  carousel_slider: ^4.1.1
  #  awesome_notifications: ^0.6.21
  flutterwave_standard: ^1.0.4
  image_picker: ^0.8.6
  cloudinary_public: ^0.21.0
  package_info_plus: ^4.0.0
  modal_bottom_sheet: ^3.0.0-pre
  flutter_inappwebview: ^5.7.2+3
  google_fonts: ^4.0.4
  firebase_crashlytics: ^3.4.6
  drop_down_list:
    git:
      url: https://github.com/quiet-programmer/drop_down_list.git
      ref: dfb7ec1
  firebase_analytics: ^10.4.0
  flutter_svg: ^2.0.6
  syncfusion_flutter_datepicker: ^23.1.43
  firebase_messaging: ^14.7.4
  get_time_ago: ^1.1.8
  otp_text_field_v2: ^1.0.3
  line_icons: ^2.0.3
  ionicons: ^0.2.2
  lucide_icons: ^0.257.0
  share_plus: ^7.1.0
  pull_to_refresh_plus: ^2.0.3
  syncfusion_flutter_barcodes: ^23.1.43
  ai_barcode_scanner: ^0.0.6
  uuid: ^4.1.0
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0

#flutter_icons:
#  android: true
#  ios: true
#  remove_alpha_ios: true
#  image_path: "assets/dev/icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/gifs/
    - assets/dev/
    - assets/icons/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
